apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  # replicas: 1
  selector:
    matchLabels:
      app: mysql
  # strategy:
    # type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: eoloplantsDB
            - name: MYSQL_ROOT_PASSWORD
              value: password
          image: mysql:5.7
          name: mysql
          ports:
            - containerPort: 3306
#      restartPolicy: Always

# SERVICE
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    app: mysql
  type: LoadBalancer