apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: planner
  name: planner 
spec:
  selector:
    matchLabels:
      app: planner
  template:
    metadata:
      labels:
        app: planner 
    spec:
      containers:
        - env:
            - name: GRPC_CLIENT_WEATHERSERVER_ADDRESS
              value: static://weatherservice:9090
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
            - name: SPRING_RABBITMQ_PASSWORD
              value: password
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              value: root
            - name: TOPO_HOST
              value: toposervice
            - name: TOPO_PORT
              value: "8080"
          image: oscarsotosanchez/planner:v1.0
          name: planner
      restartPolicy: OnFailure