apiVersion: apps/v1
kind: Deployment
metadata: 
  name: rabbitmq
spec:
  # replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  # strategy:
  #   type: Recreate
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - env:
            - name: RABBITMQ_DEFAULT_PASS
              value: password
            - name: RABBITMQ_DEFAULT_USER
              value: root
          image: rabbitmq:3-management
          name: rabbitmq
          ports:
            - containerPort: 5672
            - containerPort: 15672
          # resources: {}
#      restartPolicy: Always
---
# service
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq  
spec:
  ports:
    - name: "5672"
      port: 5672
      targetPort: 5672
    - name: "15672"
      port: 15672
      targetPort: 15672
  selector:
    app: rabbitmq
  type: LoadBalancer