apiVersion: v1
kind: Deployment
metadata:
  name: server 
spec:
  # selector:
  #   matchLabels:
  #     app: 'server'
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - args:
            - bash
            - -c
            - ' ./wait-for-it.sh mysql:3306 -- ./wait-for-it.sh rabbitmq:5672 -- node src/server.js'
          env:
            - name: MYSQL_DB
              value: eoloplantsDB
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_PASS
              value: password
            - name: MYSQL_USER
              value: root
            - name: RABBITMQ_URL
              value: amqp://root:password@rabbitmq
          image: oscarsotosanchez/server:v1.0
          name: server
          ports:
            - containerPort: 3000
      restartPolicy: OnFailure 
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app: server 
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    app: server
  type: LoadBalancer
 
