apiVersion: v1
kind: Deployment
metadata:
  name: toposervice 
spec:
  selector:
    matchLabels:
      app: toposervice
  template:
    metadata:
      labels:
        app: toposervice
    spec:
      containers:
        - env:
            - name: SPRING_DATA_MONGODB_AUTHENTICATION-DATABASE
              value: admin
            - name: SPRING_DATA_MONGODB_DATABASE
              value: topoDB
            - name: SPRING_DATA_MONGODB_HOST
              value: mongodb
            - name: SPRING_DATA_MONGODB_PASSWORD
              value: password
            - name: SPRING_DATA_MONGODB_PORT
              value: "27017"
            - name: SPRING_DATA_MONGODB_USERNAME
              value: root
          image: oscarsotosanchez/toposervice:v1.0
          name: toposervice
          ports:
            - containerPort: 8080
      restartPolicy: OnFailure
# Service
--- 
apiVersion: v1
kind: Service
metadata:
  name: toposervice
  labels:
    app: toposervice 
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: toposervice
  type: LoadBalancer