apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: weatherservice
  name: weatherservice
spec:
  selector:
    matchLabels:
      app: weatherservice
  template:
    metadata:
      labels:
        app: weatherservice
    spec:
      containers:
        - env:
            - name: GRPC_HOST
              value: weatherservice
            - name: GRPC_PORT
              value: "9090"
          image: oscarsotosanchez/weatherservice:v1.0
          name: weatherservice
          ports:
            - containerPort: 9090
      restartPolicy: OnFailure

# Service
---
apiVersion: v1
kind: Service
metadata:
  name: weatherservice
  labels:
    app: weatherservice 
spec:
  ports:
    - name: "9090"
      port: 9090
      targetPort: 9090
  selector:
    app: weatherservice
  type: LoadBalancer
